#Test data on furfural for cifit
furfural in cd2cl2 at 175 K, June 6/94

#two sites, one process
2 1

#1/T1 for each site
.177 .24

#M(infinity) 
.0973 .9830

#and M(0) for each site
.0997 -.8768

#rate for the process
.36

#and two non-zero off-diagonal elements
#note that since there are unequal populations
#the off-diagonal elements are not equal, and
#must be the right way around
2 
0 1 .1
1 0 1
